language: python
cache:
  - apt
  - directories:
    - $HOME/.pip-cache/
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
install:
#  - env
#  - make pip
  - make VIRTUAL_ENV=$VIRTUAL_ENV tests-deps
  - make VIRTUAL_ENV=$VIRTUAL_ENV pip-deps
  - make VIRTUAL_ENV=$VIRTUAL_ENV update
  - make VIRTUAL_ENV=$VIRTUAL_ENV build
  - make VIRTUAL_ENV=$VIRTUAL_ENV install
# command to run tests
script:
  - nosetests --cover-package=libopenzwave,openzwave --with-coverage
# package dependencies
before_install:
  #- env
  #- sudo -E env
  - sudo apt-get update -y -qq
  - sudo -E make VIRTUAL_ENV=$VIRTUAL_ENV common-deps
  - sudo -E make VIRTUAL_ENV=$VIRTUAL_ENV cython-deps
